
# Needed for the jekyll 2.0 migration.
relative_permalinks: true

# Meta-information about my site and blog.
title:          Andrew Hoyer
author:         Andrew Hoyer
description:    Personal playground for Andrew Hoyer
url:            http://www.andrew-hoyer.com

exclude:
  - blog_archive
  - deploy.sh
  - Gemfile
  - Gemfile.lock
  - README.md
